language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="4.0.x-dev"

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer install --prefer-dist
  - composer update

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=framework/phpcs.xml.dist src/ tests/ ; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
